### ISSUE TITLE
About platform...

### ISSUE THREAD

**Issue by zclongpop123** [pyqt/maya2015-qt4#2]
So, this just can use on windows, if we need mac and linux, we must build a new one?

**Comment by mottosso** [comment]
Unfortunately, yes. :(

**Comment by mottosso** [comment]
If other platforms are of interest, I was planning on renaming the repository to `maya2015-qt4-win`, and have `maya2015-qt4-osx` and `maya2015-qt4-debian` and so forth. Let me know if this is something you would be interested in compiling for.

**Comment by zclongpop123** [comment]
Now, we don't use other platforms, If we need that, I will tell you when I build it ..... but I haven't Linux computer....

**Comment by mottosso** [comment]
No problem, thanks for the offer. If there's anything else, feel free to comment and I'll re-open the issue.

**Comment by zclongpop123** [comment]
And thank you for help me to learn this, If I have any other questions on CG, may I ask you too?

**Comment by mottosso** [comment]
Sure, if it isn't related to Qt, it's better you use my email.
marcus@abstractfactory.io
